# Generated by Django 4.0.3 on 2022-05-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_order_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Customers',
            new_name='customers',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Product',
            new_name='product',
        ),
    ]
